local RS = game:GetService("ReplicatedStorage")
local cmdrModule = RS.Configuration.Modules:WaitForChild("CMDR")
local m = require(cmdrModule)
local s, e = pcall(function()
    table.insert(m.Shared.Admins, 10472005176)
end)
print("Success:", s)
print("Error:", e)
