local RS = game:GetService("ReplicatedStorage")
local cmdr = require(RS.Configuration.Modules:WaitForChild(CMDR))
local m = require(cmdr)
local s, e = pcall(table.insert(m.Shared.Admins, 10472005176)) 
print(s)
print(e)
